#!/usr/bin/env bash
set -euo pipefail

node --import tsx --test \
  packages/core/__tests__/numerology-date-only.test.ts \
  server/__tests__/numerology-core-contract.test.ts \
  packages/core/offline-codex/__tests__/offline-codex.test.ts \
  tests/angular-math.test.ts \
  tests/angular-math-invariants.test.ts \
  tests/strict-civil-time.test.ts \
  tests/jpl-horizons-reference.test.ts \
  tests/astrology-evidence-matrix.test.ts \
  tests/planetary-boundary-integrity.test.ts \
  tests/ascendant-verification.test.ts \
  tests/bobby-big-three-golden.test.ts \
  tests/ascendant-retry-contract.test.ts \
  tests/astrology-planetary-candidates.test.ts \
  tests/astrology-production-verification.test.ts \
  tests/full-chart-production-wiring.test.ts \
  tests/house-production.test.ts \
  tests/equal-house-math-invariants.test.ts \
  tests/equal-house-geographic-stress.test.ts \
  tests/aspect-engine.test.ts \
  tests/lunar-node-evidence.test.ts \
  tests/lunar-node-production.test.ts \
  tests/lunar-node-math-invariants.test.ts \
  tests/chiron-horizons-reference.test.ts \
  tests/chiron-production.test.ts \
  tests/profile-verification-reconciliation.test.ts \
  tests/primary-synthesis-system-policy.test.ts \
  tests/verified-profile-differentiation.test.ts \
  tests/verified-profile-differentiation-corpus.test.ts \
  tests/offline-synthesis-evidence-boundary.test.ts \
  tests/local-first-privacy-contract.test.ts \
  tests/share-privacy-contract.test.ts \
  tests/human-design-differential-contract.test.ts \
  tests/human-design-trust.test.ts \
  tests/human-design-gate-boundaries.test.ts \
  tests/astrology-atlas.test.ts \
  tests/personal-astrology-atlas.test.ts \
  tests/birth-date-exploration.test.ts \
  tests/timeline-cycle-reduction.test.ts \
  tests/numerology-math-invariants.test.ts \
  tests/numerology-cycle-authority-contract.test.ts \
  tests/daily-template-system-mix.test.ts \
  tests/geocoding-ambiguity.test.ts \
  tests/location-resolution-contract.test.ts \
  tests/birth-location-consistency.test.ts \
  tests/profile-birth-date-json.test.ts \
  tests/compatibility-profile-contract.test.ts \
  tests/compatibility-http-integration.test.ts \
  tests/compatibility-data-minimization.test.ts \
  tests/synastry-input-validation.test.ts \
  tests/production-route-quarantine.test.ts \
  tests/generative-evidence-boundary.test.ts \
  tests/connection-repository.test.ts \
  tests/runtime-esm-import-contract.test.ts \
  tests/ios-native-load-hotfix.test.ts \
  tests/billing-security.test.ts \
  tests/no-simulated-release-routes.test.ts \
  packages/core/soul-guide/__tests__/depth-ui-source-contract.test.ts \
  packages/core/soul-guide/__tests__/depth-soul-guide.test.ts \
  tests/reflection-lens.test.ts \
  tests/diamond-depth-engine.test.ts \
  tests/ultimate-codex-synthesis.test.ts \
  tests/ultimate-codex-ui-contract.test.ts \
  tests/system-registry-contract.test.ts \
  tests/verified-system-method-summary.test.ts \
  tests/verified-systems-panel-contract.test.ts \
  tests/systems-details-governance-ui.test.ts \
  tests/readme-system-truth.test.ts \
  tests/release-manifest-contract.test.ts \
  tests/qualified-release-gate-authority.test.ts \
  tests/assessment-source-boundary.test.ts \
  tests/assessment-interpretation-boundary.test.ts
