export const PHASES = {
    Ignition: {
        name: "Ignition",
        summary: "A raw-start period where identity, direction, and energy are being lit from scratch. You are building momentum before you have proof it will work.",
        focus: "Launch the things you have been delaying. Establish a physical routine and clear a single primary direction.",
        do: [
            "Start the project or relationship with no expectation of immediate return",
            "Set a 12-month target you can track weekly",
            "Build small daily habits that compound over the year",
            "Say yes to unfamiliar situations that stretch your current frame",
        ],
        dont: [
            "Demand immediate results — the payoff is downstream",
            "Overcommit to too many directions at once",
            "Rely on external validation before you have built anything",
            "Ignore the signals from your body — energy is your main resource right now",
        ],
        next: "Exposure",
    },
    Exposure: {
        name: "Exposure",
        summary: "What you built is now visible to others. Feedback — wanted and unwanted — arrives. You are learning what the world reflects back.",
        focus: "Receive input without immediately reacting. Distinguish useful signal from noise.",
        do: [
            "Show your work even when it feels unfinished",
            "Ask specific questions rather than waiting for generic praise",
            "Document what lands and what doesn't — this data is gold",
            "Build relationships with people who give honest responses",
        ],
        dont: [
            "Collapse under criticism or inflate under praise",
            "Over-explain your work before it speaks for itself",
            "Withdraw because the feedback is uncomfortable",
            "Confuse visibility with validation — they are not the same",
        ],
        next: "Construction",
    },
    Construction: {
        name: "Construction",
        summary: "A grind phase. The vision exists; now comes the unglamorous work of building the actual structure. Discipline beats inspiration here.",
        focus: "Show up to the unsexy tasks. Build systems, not just outputs.",
        do: [
            "Break the main goal into quarterly milestones",
            "Remove distractions from your working environment deliberately",
            "Invest in skills that eliminate your current bottlenecks",
            "Sleep, train, and eat with the same seriousness as your work",
        ],
        dont: [
            "Chase novelty when the current project needs depth",
            "Wait for motivation — operate on schedule instead",
            "Confuse busyness with progress",
            "Skip the boring infrastructure (finances, health, systems) for the exciting outputs",
        ],
        next: "Expansion",
    },
    Expansion: {
        name: "Expansion",
        summary: "Doors open. Reach extends. This is a natural growth window where what you built gains traction and new opportunities arrive.",
        focus: "Capitalize selectively. Not every open door deserves a yes.",
        do: [
            "Take the risk that has been justified by the work you have done",
            "Say yes to collaborations that bring in skills you do not have",
            "Increase your physical and social range — both are relevant now",
            "Invest in the infrastructure to hold more than you currently carry",
        ],
        dont: [
            "Expand faster than your foundation can support",
            "Neglect the relationships that enabled the growth",
            "Assume expansion is permanent — use the window intentionally",
            "Stretch so thin that quality drops",
        ],
        next: "Friction",
    },
    Friction: {
        name: "Friction",
        summary: "Resistance increases. What has been working stops working easily. The old structure is being stress-tested.",
        focus: "Identify what is genuinely worth preserving versus what needs to be released.",
        do: [
            "Treat obstacles as diagnostic tools — they reveal structural weaknesses",
            "Have the hard conversations you have been deferring",
            "Cut what no longer serves the core direction",
            "Increase recovery practices: sleep, movement, solitude",
        ],
        dont: [
            "Force outcomes through sheer will when the environment is pushing back",
            "Blame external forces for internal alignment issues",
            "Make permanent decisions at the peak of frustration",
            "Isolate — friction phases require honest outside perspectives",
        ],
        next: "Refinement",
    },
    Refinement: {
        name: "Refinement",
        summary: "The noise has cleared. You are tightening what remains. This is a precision phase — less about volume, more about quality.",
        focus: "Eliminate the good so the excellent can breathe.",
        do: [
            "Audit your commitments and cut the ones that dilute your strongest work",
            "Go deeper into one skill rather than spreading across many",
            "Establish non-negotiable standards for your outputs and relationships",
            "Allow yourself to be deliberate and slow — this phase rewards patience",
        ],
        dont: [
            "Mistake refinement for withdrawal — stay in motion",
            "Pursue perfection at the cost of completion",
            "Ignore emotional and relational refinement in favor of only work",
            "Rush into the next phase before the current one is consolidated",
        ],
        next: "Integration",
    },
    Integration: {
        name: "Integration",
        summary: "Multiple threads of your life are converging. What seemed unrelated is showing you the pattern. This is a synthesis phase.",
        focus: "Connect the dots between your past work, present state, and future direction.",
        do: [
            "Spend time reviewing the last 3-7 years with honest eyes",
            "Articulate what you have actually learned — write it down",
            "Allow relationships and projects to deepen rather than expand",
            "Let the synthesis reveal the next cycle's starting point",
        ],
        dont: [
            "Force integration to happen faster than it naturally unfolds",
            "Jump into a new Ignition before consolidating what you have built",
            "Dismiss old experiences as irrelevant — they are the source material now",
            "Treat depth as stagnation — you are consolidating, not stalling",
        ],
        next: "Legacy",
    },
    Legacy: {
        name: "Legacy",
        summary: "You are now building beyond yourself — for others, for the future, for something that outlasts your immediate needs.",
        focus: "What do you want to leave behind, and who needs what you have built?",
        do: [
            "Identify who comes after you and what they will need",
            "Document and transmit the knowledge you have accumulated",
            "Make investments — financial, relational, intellectual — with a long horizon",
            "Let go of the need to control outcomes; plant seeds with good soil",
        ],
        dont: [
            "Treat legacy as something that only happens at the end of life",
            "Hold onto structures or positions out of identity rather than utility",
            "Underestimate how much the quality of your inner life shapes what you leave behind",
            "Skip the Ignition seeds — legacy phases often contain the quiet start of the next cycle",
        ],
        next: "Ignition",
    },
};
